/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 woman.gltf --transform
Author: Rajibuzzaman.Khan (https://sketchfab.com/Rajibuzzaman.Khan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/womens-corset-and-pant-de9eabf8d76c4889b88011c83394b180
Title: Womens Corset And Pant
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/woman-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0}>
        <group scale={10}>
          <mesh geometry={nodes.womens_corset_and_pant_Denim_Lightweight_FRONT_2776_0.geometry} material={materials.Denim_Lightweight_FRONT_2776} />
          <mesh geometry={nodes.womens_corset_and_pant_Denim_Lightweight_Copy_1_FRONT_2785_0.geometry} material={materials.Denim_Lightweight_FRONT_2776} />
          <mesh geometry={nodes.womens_corset_and_pant_Knit_Cotton_Jersey_Green_FRONT_15835_0.geometry} material={materials.Knit_Cotton_Jersey_Green_FRONT_15835} />
          <mesh geometry={nodes.womens_corset_and_pant_Fabric3034808_FRONT_12353_0.geometry} material={materials.Fabric3034808_FRONT_12353} />
          <mesh geometry={nodes.womens_corset_and_pant_Material2994_0.geometry} material={materials.Material2994} />
          <mesh geometry={nodes.womens_corset_and_pant_Material2994_0_1.geometry} material={materials.Material2994} />
          <mesh geometry={nodes.womens_corset_and_pant_Material2994_0_2.geometry} material={materials.Material2994} />
          <mesh geometry={nodes.womens_corset_and_pant_Material2994_0_3.geometry} material={materials.Material2994} />
          <mesh geometry={nodes.womens_corset_and_pant_Material16027_0.geometry} material={materials.Material2994} />
          <mesh geometry={nodes.womens_corset_and_pant_Material15904_0.geometry} material={materials.Material2994} />
          <mesh geometry={nodes.womens_corset_and_pant_Material16150_0.geometry} material={materials.Material2994} />
          <mesh geometry={nodes.womens_corset_and_pant_Material3034654_0.geometry} material={materials.Material3034654} />
          <mesh geometry={nodes.womens_corset_and_pant_Material3034812_0.geometry} material={materials.Material3034654} />
          <mesh geometry={nodes.womens_corset_and_pant_Material3034814_0.geometry} material={materials.Material3034654} />
          <mesh geometry={nodes.womens_corset_and_pant_Material3034816_0.geometry} material={materials.Material3034654} />
        </group>
        <group scale={10}>
          <mesh geometry={nodes.shoes_r_Shape_Material13340_0.geometry} material={materials.Material13340} />
          <mesh geometry={nodes.shoes_r_Shape_Material13345_0.geometry} material={materials.Material13345} />
          <mesh geometry={nodes.shoes_r_Shape_Material13349_0.geometry} material={materials.Material13345} />
        </group>
        <group scale={10}>
          <mesh geometry={nodes.shoes_l_Shape_Material13362_0.geometry} material={materials.Material13340} />
          <mesh geometry={nodes.shoes_l_Shape_Material13366_0.geometry} material={materials.Material13345} />
          <mesh geometry={nodes.shoes_l_Shape_Material13369_0.geometry} material={materials.Material13345} />
        </group>
        <group scale={10}>
          <mesh geometry={nodes.body_Material13454_0.geometry} material={materials.Material13454} />
          <mesh geometry={nodes.body_Material13458_0.geometry} material={materials.Material13458} />
          <mesh geometry={nodes.body_Material13462_0.geometry} material={materials.Material13462} />
          <mesh geometry={nodes.body_Material13466_0.geometry} material={materials.Material13466} />
        </group>
        <group scale={10}>
          <mesh geometry={nodes.hair_Shape_Mara_shortcut_hair_Quad_opencollada_hair_ntr_0.geometry} material={materials.Mara_shortcut_hair_Quad_opencollada_hair_ntr} />
          <mesh geometry={nodes.hair_Shape_Mara_shortcut_hair_Quad_opencollada_hair01_0.geometry} material={materials.Mara_shortcut_hair_Quad_opencollada_hair01} />
          <mesh geometry={nodes.hair_Shape_Mara_shortcut_hair_Quad_opencollada_dum_0.geometry} material={materials.Material13340} />
        </group>
        <mesh geometry={nodes.eye_L_Material13473_0.geometry} material={materials.Material13473} scale={10} />
        <mesh geometry={nodes.eye_R_Material13480_0.geometry} material={materials.Material13473} scale={10} />
        <mesh geometry={nodes.eyelash_L_Material13486_0.geometry} material={materials.Material13486} scale={10} />
        <mesh geometry={nodes.eyelash_R_Material13493_0.geometry} material={materials.Material13486} scale={10} />
        <mesh geometry={nodes.tooth_Material13499_0.geometry} material={materials.Material13499} scale={10} />
      </group>
    </group>
  )
}

useGLTF.preload('/woman-transformed.glb')
